v0017

diff --git a/oneBash b/oneBash
--- a/oneBash
+++ b/oneBash
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# nvOC v0016 by fullzero
+# nvOC v0017 by fullzero
 #
 # Open a terminal to launch miner; will auto launch on boot
 #
@@ -8,18 +8,22 @@
 #
 # click the Desktop Sharing icon on the left for RDP 
 #
-# ifconfig (outputs at beginning of mining process) will show your rig IP
+# your rig IP displays at beginning of mining process
+#
+# worker names will default to your rig host address (last 3 digits of rig IP)
 #
 # USE ALL CAPS
 #
 # CHOOSE COIN FROM:
-# ZEC  NICE  VTC  ZEN  DGB  SIA  ZCL  FTC  LBC  MUSIC  ETC  EXP  ETH  DCR  PASC
+# ZEC   ZCOIN  HUSH   ZEN  ZCL  
+# NICE  ETH    MUSIC  ETC  EXP  DCR  PASC
+# MONA  VTC    DGB    SIA  FTC  LBC  
 # DUAL_ETC_DCR    DUAL_ETC_PASC    DUAL_ETC_LBC    DUAL_ETC_SC
 # DUAL_EXP_DCR    DUAL_EXP_PASC    DUAL_EXP_LBC    DUAL_EXP_SC
 # DUAL_ETH_DCR    DUAL_ETH_PASC    DUAL_ETH_LBC    DUAL_ETH_SC
 # DUAL_MUSIC_DCR  DUAL_MUSIC_PASC  DUAL_MUSIC_LBC  DUAL_MUSIC_SC
 
-COIN="ZEC"
+COIN="NICE"
 
 TEAMVIEWER="NO"                 # YES NO
 
@@ -37,11 +41,14 @@ MANUAL_FAN="YES"             	# YES NO
 # Set fan speed if MANUAL_FAN="YES"
 FAN_SPEED=75
 
+# If you are using a slow USB Key
+SLOW_USB_KEY_MODE="NO"        	# YES NO
+
 # Mine XMR with CPU
 plusCPU="NO"		        # YES NO
 
 # Number of threads for plusCPU
-threadCOUNT="1"                 	# varies per CPU
+threadCOUNT="1"                 # varies per CPU
 
 
 INDIVIDUAL_CLOCKS="NO"      	# YES NO
@@ -125,88 +132,125 @@ INDIVIDUAL_POWERLIMIT_13=125
 # change EWBF_PERCENT to alter donation percent for EWBF Miner
 EWBF_PERCENT=0
 
+
+# IP as worker implementation
+########################################################################################
+IPW=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
+# for_full_IP with _ instead of .
+#IP_AS_WORKER=$(echo $IPW | sed 'y/./_/')
+echo ""
+# using only host address
+IP_AS_WORKER=$(echo -n $IPW | tail -c -3)
+echo workername: $IP_AS_WORKER
+########################################################################################
+
+
 # set YOUR ADDRESSES, WORKERS, POOL and PORT:
-ZEC_WORKER="nvOC"
+ZEC_WORKER="$IP_AS_WORKER"
 ZEC_ADDRESS="t1XfkZUZWME8FnRiFxHZQAQ2K1UdQMbshJp"
 ZEC_POOL="zec-us-east1.nanopool.org"
 ZEC_PORT="6666"
+
+
 EWBF_VERSION="3_4"  # choose 3_3  or  3_4
 
-ZCL_WORKER="nvOC"
+
+ZCL_WORKER="$IP_AS_WORKER"
 ZCL_ADDRESS="fullzero22"
 ZCL_POOL="zcl.coinmine.pl"
 ZCL_PORT="7007"
 
-ZEN_WORKER="nvOC"
+ZEN_WORKER="$IP_AS_WORKER"
 ZEN_ADDRESS="znictSisUCALijmhJrjLS8FozvcJRAiHc29"
 ZEN_POOL="us.zenmine.pro"
 ZEN_PORT="9009"
 
+HUSH_WORKER="$IP_AS_WORKER"
+HUSH_ADDRESS="fullzero22"
+HUSH_POOL="zdash.suprnova.cc"
+HUSH_PORT="4048"
+
+ZCOIN_WORKER="$IP_AS_WORKER"
+ZCOIN_ADDRESS="fullzero22"
+ZCOIN_POOL="stratum+tcp://xzc.suprnova.cc:1569"
+
+MONA_WORKER="$IP_AS_WORKER"
+MONA_ADDRESS="fullzero22"
+MONA_POOL="stratum+tcp://mona.suprnova.cc:2995"
+
 # if YES ensure you update BTC_ADDRESS
 VTC_AUTOCONVERT_TO_BTC="YES"        #YES  NO
-VTC_WORKER="nvOC"
+VTC_WORKER="$IP_AS_WORKER"
 VTC_ADDRESS="VsvtYL2mz3YFM3fpt5pb28zHodTbnJodRc"
 VTC_POOL="stratum+tcp://lyra2v2.mine.zpool.ca:4533"
 
 BTC_ADDRESS="18Y5HYe3BAwAhTAkFLbD52o8NqtrN3DtpF"
 
 # NICE autoconverts to BTC: ensure you update BTC_ADDRESS if you use NICE
-NICE_WORKER="nvOC"
+NICE_WORKER="$IP_AS_WORKER"
 NICE_POOL="stratum+tcp://daggerhashimoto.usa.nicehash.com:3353"
+GENOIL_NICE_POOL="daggerhashimoto.usa.nicehash.com:3353"
 NICE_EXTENTION_ARGUMENTS=""   # add any additional claymore arguments desired here
 
 # if YES ensure you update BTC_ADDRESS
 DGB_AUTOCONVERT_TO_BTC="YES"        #YES  NO
-DBG_INTENSITY=26
+DGB_INTENSITY=26
 DGB_ADDRESS="DKhCswL8Ff5UyZWdVEbyUVvDhLYMmfVLP7"
 DGB_POOL="stratum+tcp://skein.mine.zpool.ca:4933"
 
-LBC_WORKER="nvOC"
+LBC_WORKER="$IP_AS_WORKER"
 LBC_ADDRESS="fullzero22"
 LBC_POOL="stratum+tcp://lbry.suprnova.cc:6256"
 
-FTC_WORKER="nvOC"
+FTC_WORKER="$IP_AS_WORKER"
 FTC_ADDRESS="fullzero22"
 FTC_POOL="stratum+tcp://coinotron.com:3337"
 
-ETC_WORKER="nvOC"
-ETC_ADDRESS="0xc3eab16bd575e5498efef2b038c8c178598d659e"
-ETC_POOL="etc-us-east1.nanopool.org:19999"
-ETC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here
+
+USE_ENVIRONMENTAL_VARIBLES="NO"   #YES  NO
 
 ETHERMINEdotORG="NO"
+
 CLAYMORE_VERSION="9_5"    # choose 9_5  or  9_4  or  8_0
 
-ETH_WORKER="nvOC"
+GENOILorCLAYMORE="GENOIL"  # choose GENOIL  or  CLAYMORE
+
+
+ETH_WORKER="$IP_AS_WORKER"
 ETH_ADDRESS="0xe12bdd454997e443ec0cae6bebb6bb3c74242aae"
 ETH_POOL="eth-us-east1.nanopool.org:9999"
 ETH_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here
 
-EXP_WORKER="nvOC"
+ETC_WORKER="$IP_AS_WORKER"
+ETC_ADDRESS="0xc3eab16bd575e5498efef2b038c8c178598d659e"
+ETC_POOL="etc-us-east1.nanopool.org:19999"
+ETC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here
+
+EXP_WORKER="$IP_AS_WORKER"
 EXP_ADDRESS="0xa7108c64e6fec3193091f2cae2a5c62a36d4396a"
 EXP_POOL="exp-us.dwarfpool.com:8018"
 EXP_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here
 
-MUSIC_WORKER="nvOC"
+MUSIC_WORKER="$IP_AS_WORKER"
 MUSIC_ADDRESS="0x48919b296f648bd2edfeb6f336d2b3f66a741ea5"
 MUSIC_POOL="stratum+tcp://213.154.202.174:3334"
 MUSIC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here
 
-SC_WORKER="nvOC"
+SC_WORKER="$IP_AS_WORKER"
 SC_ADDRESS="1569a3353bb3353aedc6e0b79e796787ffcbe45d6caaa28f678ba74a5c50fdb02e735244e706"
 SC_POOL="sia-us-east1.nanopool.org:7777"
 SC_GW_POOL="sia-us-east1.nanopool.org:9980"
 
-DCR_WORKER="nvOC"
+DCR_WORKER="$IP_AS_WORKER"
 DCR_ADDRESS="fullzero22"
 DCR_POOL="stratum+tcp://dcr.suprnova.cc:3252"
 
-PASC_WORKER="nvOC"
+PASC_WORKER="$IP_AS_WORKER"
 PASC_ADDRESS="86646-64.b12a9833f216b5a8"
 PASC_POOL="pasc-us-east1.nanopool.org:15555"
 
 # if plusCPU is "YES" replace with your XMR info
-XMR_WORKER="nvOC"
+XMR_WORKER="$IP_AS_WORKER"
 XMR_ADDRESS="47sghzufGhJJDQEbScMCwVBimTuq6L5JiRixD8VeGbpjCTA12noXmi4ZyBZLc99e66NtnKff34fHsGRoyZk3ES1s1V4QVcB.23d5f83d0021a50d8f809f4727c8622d3ea25798942bcb1ba0eee40cc157f65c"
 XMR_POOL="stratum+tcp://xmr-us-east1.nanopool.org:14444"
 
@@ -232,6 +276,12 @@ then
 XORG="OK"
 fi
 
+sudo ldconfig /usr/local/cuda/lib64
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
+
 if [ $XORG == "FAIL" ]
 then
 sudo cp '/etc/X11/xorg.conf.backup' '/etc/X11/xorg.conf'
@@ -245,11 +295,30 @@ sleep 5
 sudo reboot
 fi
 
-echo ''
-echo ifconfig:
-echo ''
+IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
 
-ifconfig
+echo ''
+echo rig IP: $IP
+
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
+
+if [ $USE_ENVIRONMENTAL_VARIBLES == "YES" ]
+then
+export GPU_FORCE_64BIT_PTR="0"
+export GPU_MAX_HEAP_SIZE="100"
+export GPU_USE_SYNC_OBJECTS="1"
+export GPU_MAX_ALLOC_PERCENT="100"
+echo ""
+echo ENVIRONMENTAL VARIBLES SET
+fi
+
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 
 if [ $POWERLIMIT == "YES" ]
 then
@@ -259,39 +328,111 @@ fi
 if [ $INDIVIDUAL_POWERLIMIT == "YES" ]
 then
 sudo nvidia-smi -i 0 -pl $INDIVIDUAL_POWERLIMIT_0
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 1 -pl $INDIVIDUAL_POWERLIMIT_1
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 2 -pl $INDIVIDUAL_POWERLIMIT_2
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 3 -pl $INDIVIDUAL_POWERLIMIT_3
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 4 -pl $INDIVIDUAL_POWERLIMIT_4
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 5 -pl $INDIVIDUAL_POWERLIMIT_5
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 6 -pl $INDIVIDUAL_POWERLIMIT_6
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 7 -pl $INDIVIDUAL_POWERLIMIT_7
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 8 -pl $INDIVIDUAL_POWERLIMIT_8
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 9 -pl $INDIVIDUAL_POWERLIMIT_9
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 10 -pl $INDIVIDUAL_POWERLIMIT_10
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 11 -pl $INDIVIDUAL_POWERLIMIT_11
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 12 -pl $INDIVIDUAL_POWERLIMIT_12
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 sudo nvidia-smi -i 13 -pl $INDIVIDUAL_POWERLIMIT_13
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 fi
 
 if [ $TEAMVIEWER == "YES" ]
 then
 sudo teamviewer --daemon enable
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 fi
 
 if [ $TEAMVIEWER == "NO" ]
 then
 sudo teamviewer --daemon disable
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 fi
 
 if [ $SSH == "YES" ]
 then
 sudo cp '/etc/init/ssh.conf-on' '/etc/init/ssh.conf'
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 fi
 
 if [ $SSH == "NO" ]
 then
 sudo cp '/etc/init/ssh.conf-off' '/etc/init/ssh.conf'
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
 fi
 
 if [ $plusCPU == "YES" ]
@@ -384,6 +525,11 @@ if [ $NORMAL == "YES" ]
 then
     TI="2 3"
 fi
+fi
+
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
 fi
 
 for j in $TI
@@ -626,6 +772,11 @@ then
 fi
 done
 
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
+
 if [ $MANUAL_FAN == "YES" ]
 then
     ${NVD} -a [gpu:0]/GPUFanControlState=1
@@ -866,6 +1017,11 @@ then
 fi
 fi
 
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
+
 if [ $MANUAL_FAN == "NO" ]
 then
     ${NVD} -a [gpu:0]/GPUFanControlState=0
@@ -1012,9 +1168,28 @@ then
 fi
 fi
 
+if [ $SLOW_USB_KEY_MODE == "YES" ]
+then
+sleep 6
+fi
+
 if [ $COIN == "NICE" ]
 then
 
+if [ $GENOILorCLAYMORE == "GENOIL" ]
+then
+HCD='/home/m1/eth/Genoil-U/ethminer'
+
+NICEADDR="$BTC_ADDRESS.$NICE_WORKER"
+until $HCD -SP 2 -S $GENOIL_NICE_POOL -O $NICEADDR:x -U
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+if [ $GENOILorCLAYMORE == "CLAYMORE" ]
+then
 if [ $CLAYMORE_VERSION == "9_5" ]
 then
 HCD='/home/m1/eth/9_5/ethdcrminer64'
@@ -1037,6 +1212,7 @@ until $HCD -epool $NICE_POOL -ewal $NICEADDR -epsw x -esm 3 -allpools 1 -estale 
    echo "FAILURE; reinit in 5" >&2
    sleep 5
 done
+fi
 fi
 
 if [ $COIN == "ZEC" ]
@@ -1102,6 +1278,52 @@ until $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $ZEN_POOL --user $ZENADD
 done
 fi
 
+if [ $COIN == "HUSH" ]
+then
+
+if [ $EWBF_VERSION == "3_3" ]
+then
+HCD='/home/m1/zec/v3_3/miner'
+fi
+
+if [ $EWBF_VERSION == "3_4" ]
+then
+HCD='/home/m1/zec/v3_4/miner'
+fi
+
+HUSHADDR="$HUSH_ADDRESS.$HUSH_WORKER"
+until $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $HUSH_POOL --user $HUSHADDR --pass z --port $HUSH_PORT;
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+if [ $COIN == "ZCOIN" ]
+then
+HCD='/home/m1/TPccminer/ccminer'
+ADDR="$ZCOIN_ADDRESS.$ZCOIN_WORKER"
+
+until $HCD -a lyra2 -o $ZCOIN_POOL -u $ADDR -p x
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+
+fi
+
+if [ $COIN == "MONA" ]
+then
+HCD='/home/m1/SPccminer/ccminer'
+ADDR="$MONA_ADDRESS.$MONA_WORKER"
+
+until $HCD -a lyra2v2 -o $MONA_POOL -u $ADDR -p x
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
 if [ $COIN == "VTC" ]
 then
 HCD='/home/m1/SPccminer/ccminer'
@@ -1137,7 +1359,7 @@ ADDR="$DGB_ADDRESS"
 if [ $DGB_AUTOCONVERT_TO_BTC == "YES" ]
 then
 ADDR="$BTC_ADDRESS"
-until $HCD -a skein -o $DGB_POOL -u $ADDR -p c=BTC -i $DBG_INTENSITY
+until $HCD -a skein -o $DGB_POOL -u $ADDR -p c=BTC -i $DGB_INTENSITY
    do
    echo "FAILURE; reinit in 5" >&2
    sleep 5
@@ -1147,7 +1369,7 @@ fi
 if [ $DGB_AUTOCONVERT_TO_BTC == "NO" ]
 then
 
-until $HCD -a skein -o $DGB_POOL -u $ADDR -p c=DGB -i $DBG_INTENSITY
+until $HCD -a skein -o $DGB_POOL -u $ADDR -p c=DGB -i $DGB_INTENSITY
    do
    echo "FAILURE; reinit in 5" >&2
    sleep 5
@@ -1182,6 +1404,26 @@ fi
 if [ $COIN == "ETC" ]
 then
 
+if [ $GENOILorCLAYMORE == "GENOIL" ]
+then
+HCD='/home/m1/eth/Genoil-U/ethminer'
+
+ETCADDR="$ETC_ADDRESS/$ETC_WORKER"
+
+if [ $ETHERMINEdotORG == "YES" ]
+then
+ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
+fi
+
+until $HCD -S $ETC_POOL -O $ETCADDR:x -U
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+if [ $GENOILorCLAYMORE == "CLAYMORE" ]
+then
 if [ $CLAYMORE_VERSION == "9_5" ]
 then
 HCD='/home/m1/eth/9_5/ethdcrminer64'
@@ -1210,10 +1452,25 @@ until $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -mode 1 -dbg -1 $ETC_EXTENTIO
    sleep 5
 done
 fi
+fi
 
 if [ $COIN == "EXP" ]
 then
 
+if [ $GENOILorCLAYMORE == "GENOIL-CURRENTLY-NOT-SUPPORTED" ]
+then
+HCD='/home/m1/eth/Genoil-U/ethminer'
+
+EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
+until $HCD -S $EXP_POOL -O $EXPADDR:x -U
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+#if [ $GENOILorCLAYMORE == "CLAYMORE" ]
+#then
 if [ $CLAYMORE_VERSION == "9_5" ]
 then
 HCD='/home/m1/eth/9_5/ethdcrminer64'
@@ -1237,10 +1494,31 @@ until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -mode 1 -allpools 1 -dbg -1 $
    sleep 5
 done
 fi
+#fi
 
 if [ $COIN == "ETH" ]
 then
 
+if [ $GENOILorCLAYMORE == "GENOIL" ]
+then
+HCD='/home/m1/eth/Genoil-U/ethminer'
+
+ETHADDR="$ETH_ADDRESS/$ETH_WORKER"
+
+if [ $ETHERMINEdotORG == "YES" ]
+then
+ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
+fi
+
+until $HCD -S $ETH_POOL -O $ETHADDR:x -U
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+if [ $GENOILorCLAYMORE == "CLAYMORE" ]
+then
 if [ $CLAYMORE_VERSION == "9_5" ]
 then
 HCD='/home/m1/eth/9_5/ethdcrminer64'
@@ -1269,10 +1547,25 @@ until $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -mode 1 -dbg -1 $ETH_EXTENTIO
    sleep 5
 done
 fi
+fi
 
 if [ $COIN == "MUSIC" ]
 then
 
+if [ $GENOILorCLAYMORE == "GENOIL-CURRENTLY-NOT-SUPPORTED" ]
+then
+HCD='/home/m1/eth/Genoil-U/ethminer'
+
+MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
+until $HCD -S $MUSIC_POOL -O $MUSICADDR:x -U
+   do
+   echo "FAILURE; reinit in 5" >&2
+   sleep 5
+done
+fi
+
+#if [ $GENOILorCLAYMORE == "CLAYMORE" ]
+#then
 if [ $CLAYMORE_VERSION == "9_5" ]
 then
 HCD='/home/m1/eth/9_5/ethdcrminer64'
@@ -1295,6 +1588,7 @@ until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -mode 1 -allpools 1 -dbg 
    sleep 5
 done
 fi
+#fi
 
 if [ $COIN == "DCR" ]
 then
